branches:
  accept:
  - "**"
files:
  accept:
  - "**.yar"
  - "**.yara"
  ignore:
  - "ignored_rules/**"
variables:
  file_name: ""
  file_type: ""
  imphash: ""
  md5: ""
  new_file: true
  positives: 0
  sha1: ""
  sha256: ""
  signatures: ""
  ssdeep: ""
  submissions: 0
  tags: ""
  vhash: ""
  # Antivirus engines
  acronis: ""
  ad_aware: ""
  aegislab: ""
  ahnlab: ""
  ahnlab_v3: ""
  alibaba: ""
  alyac: ""
  antivir7: ""
  antivir: ""
  antiy_avl: ""
  apex: ""
  arcabit: ""
  avast: ""
  avast_mobile: ""
  avg: ""
  avira: ""
  avware: ""
  babable: ""
  baidu: ""
  bitdefender: ""
  bitdefendertheta: ""
  bkav: ""
  cat_quickheal: ""
  clamav: ""
  cmc: ""
  commtouch: ""
  comodo: ""
  crowdstrike: ""
  cybereason: ""
  cylance: ""
  cynet: ""
  cyren: ""
  drweb: ""
  egambit: ""
  elastic: ""
  emsisoft: ""
  endgame: ""
  escan: ""
  eset_nod32: ""
  f_prot: ""
  f_secure: ""
  fireeye: ""
  fortinet: ""
  gdata: ""
  ikarus: ""
  invincea: ""
  jiangmin: ""
  k7antivirus: ""
  k7gw: ""
  kaspersky: ""
  kingsoft: ""
  malwarebytes: ""
  max: ""
  maxsecure: ""
  mcafee: ""
  mcafee_gw_edition: ""
  microsoft: ""
  microworld_escan: ""
  nano_antivirus: ""
  nod32: ""
  nprotect: ""
  paloalto: ""
  panda: ""
  prevx1: ""
  qihoo_360: ""
  rising: ""
  sangfor: ""
  sentinelone: ""
  sophos: ""
  sunbelt: ""
  superantispyware: ""
  symantec: ""
  symantecmobileinsight: ""
  tachyon: ""
  tencent: ""
  thehacker: ""
  totaldefense: ""
  trapmine: ""
  trendmicro: ""
  trendmicro_housecall: ""
  trustlook: ""
  vba32: ""
  vipre: ""
  virobot: ""
  webroot: ""
  whitearmor: ""
  yandex: ""
  zillya: ""
  zonealarm: ""
  zoner: ""
